name: font_awesome_flutter_devtools_extension
description: "A DevTools extension for package:font_awesome_flutter."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  devtools_app_shared: ^0.2.1
  devtools_extensions: ^0.2.1
  flutter:
    sdk: flutter
  font_awesome_flutter:
    path: ../font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  devtools_app_shared: 
    path: ../../../devtools/packages/devtools_app_shared
  devtools_extensions: 
    path: ../../../devtools/packages/devtools_extensions
  devtools_shared: 
    path: ../../../devtools/packages/devtools_shared
